package view;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UIManager;
import model.Funcionario;
import resources.graphicComponents.FontLoader;
import resources.utilitaries.Utilitaries;

/**
 *
 * @author ferreiraluizga
 */
public class Dashboard extends javax.swing.JFrame {

    Funcionario func;
    
    public Dashboard() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/img/app_logo.png")));
        setExtendedState(MAXIMIZED_BOTH);
        styleSidebarComponents(sidebar_menu1);
        styleSidebarComponents(sidebar_menu2);
        styleSidebarComponents(sidebar_menu3);
        styleSidebarComponents(sidebar_menu4);
        styleSidebarComponents(sidebar_menu5);
        styleSidebarComponents(sidebar_menu6);
        styleSidebarComponents(sidebar_menu7);
    }
    
    public Dashboard(Funcionario func) {
        this.func = func;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/img/app_logo.png")));
        setExtendedState(MAXIMIZED_BOTH);
        lblUser.setText(func.getNome_Func());
        lblCargo.setText(Utilitaries.verificarCargo(func.getCod_Cargo()));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lblDateTime.setText(Utilitaries.getHoraAtual() + " | " + Utilitaries.setDataAtual());
            }
        });
        timer.start();
        styleSidebarComponents(sidebar_menu1);
        styleSidebarComponents(sidebar_menu2);
        styleSidebarComponents(sidebar_menu3);
        styleSidebarComponents(sidebar_menu4);
        styleSidebarComponents(sidebar_menu5);
        styleSidebarComponents(sidebar_menu6);
        styleSidebarComponents(sidebar_menu7);
    }
    
    private void styleSidebarComponents(JButton button) {
        button.putClientProperty(FlatClientProperties.OUTLINE, false);
        button.putClientProperty(FlatClientProperties.STYLE,
                "background: #00000000; "
                + "foreground: #FFFFFF; "
        );
        button.setFocusPainted(false);
        button.setHorizontalAlignment(SwingConstants.LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new resources.graphicComponents.GradientPanel();
        imageAvatar1 = new resources.graphicComponents.ImageAvatar();
        lblUser = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        sidebar_menu1 = new javax.swing.JButton();
        sidebar_menu2 = new javax.swing.JButton();
        sidebar_menu3 = new javax.swing.JButton();
        sidebar_menu4 = new javax.swing.JButton();
        sidebar_menu5 = new javax.swing.JButton();
        sidebar_menu6 = new javax.swing.JButton();
        sidebar_menu7 = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_config = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        menu_config1 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        menu_config2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menu_config3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menu_config4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEXO: Dashboard");

        gradientPanel1.setGradientColor1(new java.awt.Color(38, 111, 163));
        gradientPanel1.setGradientColor2(new java.awt.Color(34, 73, 104));

        lblUser.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("Funcionario");

        lblDateTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTime.setText("HH:mm:ss DD/MM/YYYY");

        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo.setText("Cargo");

        sidebar_menu1.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu1.setText("Menu Teste");
        sidebar_menu1.setBorder(null);
        sidebar_menu1.setBorderPainted(false);
        sidebar_menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu1.setIconTextGap(10);
        sidebar_menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu1MouseExited(evt);
            }
        });

        sidebar_menu2.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu2.setText("Menu Teste");
        sidebar_menu2.setBorder(null);
        sidebar_menu2.setBorderPainted(false);
        sidebar_menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu2.setIconTextGap(10);
        sidebar_menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu2MouseExited(evt);
            }
        });

        sidebar_menu3.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu3.setText("Menu Teste");
        sidebar_menu3.setBorder(null);
        sidebar_menu3.setBorderPainted(false);
        sidebar_menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu3.setIconTextGap(10);
        sidebar_menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu3MouseExited(evt);
            }
        });

        sidebar_menu4.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu4.setText("Menu Teste");
        sidebar_menu4.setBorder(null);
        sidebar_menu4.setBorderPainted(false);
        sidebar_menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu4.setIconTextGap(10);
        sidebar_menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu4MouseExited(evt);
            }
        });

        sidebar_menu5.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu5.setText("Menu Teste");
        sidebar_menu5.setBorder(null);
        sidebar_menu5.setBorderPainted(false);
        sidebar_menu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu5.setIconTextGap(10);
        sidebar_menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu5MouseExited(evt);
            }
        });

        sidebar_menu6.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu6.setText("Menu Teste");
        sidebar_menu6.setBorder(null);
        sidebar_menu6.setBorderPainted(false);
        sidebar_menu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu6.setIconTextGap(10);
        sidebar_menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu6MouseExited(evt);
            }
        });

        sidebar_menu7.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/config.svg")));
        sidebar_menu7.setText("Menu Teste");
        sidebar_menu7.setBorder(null);
        sidebar_menu7.setBorderPainted(false);
        sidebar_menu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_menu7.setIconTextGap(10);
        sidebar_menu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebar_menu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidebar_menu7MouseExited(evt);
            }
        });

        separator.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(sidebar_menu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_menu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addGap(24, 24, 24)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(sidebar_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidebar_menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblDateTime)
                .addContainerGap())
        );

        menu_config.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/settings.svg")));
        menu_config.setText("Configurações");

        jMenuItem19.setText("Alterar Informações de Login");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        menu_config.add(jMenuItem19);

        jMenuItem20.setText("Encerrar Sessão");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        menu_config.add(jMenuItem20);

        jMenuItem21.setText("Sair");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        menu_config.add(jMenuItem21);

        jMenuBar1.add(menu_config);

        menu_config1.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/users.svg")));
        menu_config1.setText("Clientes");

        jMenu1.setText("Clientes");

        jMenuItem15.setText("Cadastrar Cliente");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuItem16.setText("Consultar Clientes");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        menu_config1.add(jMenu1);

        jMenu2.setText("NEXOClub");

        jMenuItem17.setText("Cadastrar Cliente no NEXOClub");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Consultar Clientes do NEXOClub");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        menu_config1.add(jMenu2);

        jMenuBar1.add(menu_config1);

        menu_config2.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/building.svg")));
        menu_config2.setText("Funcionários");

        jMenu3.setText("Funcionários");

        jMenuItem11.setText("Cadastrar Funcionários");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Consultar Funcionários");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        menu_config2.add(jMenu3);

        jMenu4.setText("Cargos");

        jMenuItem13.setText("Cadastrar Cargos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Consultar Cargos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        menu_config2.add(jMenu4);

        jMenuBar1.add(menu_config2);

        menu_config3.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/products.svg")));
        menu_config3.setText("Produtos");

        jMenu5.setText("Produtos");

        jMenuItem3.setText("Cadastrar Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Consultar Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        menu_config3.add(jMenu5);

        jMenu6.setText("Categorias");

        jMenuItem5.setText("Cadastrar Categorias");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Consultar Categorias");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        menu_config3.add(jMenu6);

        jMenu7.setText("Marcas");

        jMenuItem7.setText("Cadastrar Marcas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Consultar Marcas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        menu_config3.add(jMenu7);

        jMenu8.setText("Fornecedores");

        jMenuItem9.setText("Cadastrar Fornecedor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Consultar Fornecedores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        menu_config3.add(jMenu8);

        jMenuBar1.add(menu_config3);

        menu_config4.setIcon(new FlatSVGIcon(getClass().getResource("/resources/img/sell.svg")));
        menu_config4.setText("Compras");

        jMenuItem1.setText("Cadastrar Compra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_config4.add(jMenuItem1);

        jMenuItem2.setText("Consultar Compras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_config4.add(jMenuItem2);

        jMenuBar1.add(menu_config4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 761, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sidebar_menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu1MouseEntered
        sidebar_menu1.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu1MouseEntered

    private void sidebar_menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu1MouseExited
        sidebar_menu1.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu1MouseExited

    private void sidebar_menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu2MouseEntered
        sidebar_menu2.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu2MouseEntered

    private void sidebar_menu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu2MouseExited
        sidebar_menu2.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu2MouseExited

    private void sidebar_menu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu3MouseEntered
        sidebar_menu3.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu3MouseEntered

    private void sidebar_menu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu3MouseExited
        sidebar_menu3.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu3MouseExited

    private void sidebar_menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu4MouseEntered
        sidebar_menu4.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu4MouseEntered

    private void sidebar_menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu4MouseExited
        sidebar_menu4.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu4MouseExited

    private void sidebar_menu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu5MouseEntered
        sidebar_menu5.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu5MouseEntered

    private void sidebar_menu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu5MouseExited
        sidebar_menu5.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu5MouseExited

    private void sidebar_menu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu6MouseEntered
        sidebar_menu6.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu6MouseEntered

    private void sidebar_menu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu6MouseExited
        sidebar_menu6.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu6MouseExited

    private void sidebar_menu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu7MouseEntered
        sidebar_menu7.putClientProperty(FlatClientProperties.STYLE,
            "background: #224968; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu7MouseEntered

    private void sidebar_menu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_menu7MouseExited
        sidebar_menu7.putClientProperty(FlatClientProperties.STYLE,
            "background: #00000000; "
            + "foreground: #FFFFFF; "
        );
    }//GEN-LAST:event_sidebar_menu7MouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    public static void main(String args[]) {
        FlatCarbonIJTheme.setup();
        UIManager.put("defaultFont", FontLoader.loadFont("Poppins.ttf", 13f));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.graphicComponents.GradientPanel gradientPanel1;
    private resources.graphicComponents.ImageAvatar imageAvatar1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu menu_config;
    private javax.swing.JMenu menu_config1;
    private javax.swing.JMenu menu_config2;
    private javax.swing.JMenu menu_config3;
    private javax.swing.JMenu menu_config4;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton sidebar_menu1;
    private javax.swing.JButton sidebar_menu2;
    private javax.swing.JButton sidebar_menu3;
    private javax.swing.JButton sidebar_menu4;
    private javax.swing.JButton sidebar_menu5;
    private javax.swing.JButton sidebar_menu6;
    private javax.swing.JButton sidebar_menu7;
    // End of variables declaration//GEN-END:variables
}
